### ISSUE TITLE
Typo in file "css/grayscale.css"

### ISSUE THREAD

**Issue by user501254** [IronSummitMedia/startbootstrap-grayscale#6]
Incorrect property name on line 96
`outline: nonte;`

possible correction
`outline: none;`

### Full block
```css
.navbar-custom .nav li.active {
    outline: none;
    background-color: rgba(255,255,255,.3);
}
```
